### ISSUE TITLE
Use with keras API

### ISSUE THREAD

**Issue by zaccharieramzi** [google-research/receptive_field#1] opened 2019-12-10 09:34 UTC
I want to compute the receptive field of my model built with `tensorflow.keras`. Is it possible and how can I do it?

I tried something like:
```python
import receptive_field as rf
import tensorflow as tf

# Construct graph.
g = tf.Graph()
with g.as_default():
    model = my_model()

# Compute receptive field parameters.
rf_x, rf_y, eff_stride_x, eff_stride_y, eff_pad_x, eff_pad_y = \
  rf.compute_receptive_field_from_graph_def( \
    g.as_graph_def(), 'input_1', 'my_target')
```

But I had multiple errors:
- `tf.logging` doesn't exist anymore.
- the nodes are not ordered correctly in `receptive_field_computation.py`
- `ValueError: Unknown layer for operation 'my_target': Placeholder`

I see this is the first issue. Is this repo still maintained?

**Comment by andrefaraujo** [comment] 2019-12-11 17:31
Yes, this repo is maintained :)

- For tf.logging, we could do something like this: https://github.com/tensorflow/tensorflow/issues/26662
- `the nodes are not ordered correctly in receptive_field_computation.py`: can you please let me know the exact error?
- The library works by whitelisting operations. Can you please let me know which ops you find are not supported? Note that most ops do not influence the receptive field and usually can be added to the list here: https://github.com/google-research/receptive_field/blob/cfbfe6baa842d4adb3dcd4bc5dcd11cfd6595483/receptive_field/python/util/parse_layer_parameters.py#L27

**Comment by zaccharieramzi** [comment] 2019-12-11 17:34
But I reckon the main problem is that the library is not meant for models defined via the `keras` API of `tensorflow` or am I wrong?

**Comment by andrefaraujo** [comment] 2019-12-11 17:39
Indeed, the library was originally designed for TF 1.X models, especially based on Slim. But it shouldn't be hard to use Keras or other APIs, since RF computation happens directly on the underlying graph.

**Comment by zaccharieramzi** [comment] 2019-12-11 18:38
Ok.
I don't remember how I did to get the original error I indicated (probably something like calling my model on a placeholder but I didn't keep the script sorry).
However, I have a minimal failing example:
```python
import receptive_field as rf
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, Input
from tensorflow.keras.models import Model

def model_build_func(input_shape=[224, 224, 3]):
    im = Input(input_shape, name='image')
    conv_im = Conv2D(1, 3, name='feature_map')(im)
    model = Model(im, conv_im)
    return model

# Construct graph.
g = tf.Graph()
with g.as_default():
    model = model_build_func(input_shape=[224, 224, 3])

# Compute receptive field parameters.
rf_x, rf_y, eff_stride_x, eff_stride_y, eff_pad_x, eff_pad_y = \
  rf.compute_receptive_field_from_graph_def( \
    g.as_graph_def(), 'image', 'feature_map')
```

If you comment out all the `tf.logging` you get the following error:
```
ValueError                                Traceback (most recent call last)
<ipython-input-4-0d1d11a1f1ab> in <module>
     18 rf_x, rf_y, eff_stride_x, eff_stride_y, eff_pad_x, eff_pad_y = \
     19   rf.compute_receptive_field_from_graph_def( \
---> 20     g.as_graph_def(), 'image', 'feature_map')

~/workspace/receptive_field/receptive_field/python/util/receptive_field_computation.py in compute_receptive_field_from_graph_def(graph_def, input_node, output_node, stop_propagation, input_resolution)
    382 
    383   if not found_output_node:
--> 384     raise ValueError("Output node was not found")
    385   if input_node not in rf_sizes_x:
    386     raise ValueError("Input node was not found")

ValueError: Output node was not found
```

I tried figuring out which node I needed to indicate as the target using `[node.name for _, (o, node, _, _) in ordered_node_info]`, but I didn't find one that didn't get a further error.

**Comment by zaccharieramzi** [comment] 2019-12-11 18:39
Also what I meant regarding the ordering of the nodes might be related to the fact that I am using the keras API, let's see.

**Comment by andrefaraujo** [comment] 2019-12-12 18:38
So, in the latest code snippet you are using an incorrect `output_node` value (`'feature_map'`) in the call to `compute_receptive_field_from_graph_def`.

You can find the correct node name by running (after constructing the graph):
```python
print([n.name for n in g.as_graph_def().node])
```

This will print out the actual node names in a list, like:
`[u'image', u'feature_map/kernel/Initializer/random_uniform/shape', u'feature_map/kernel/Initializer/random_uniform/min', (...), u'feature_map/Conv2D', (...)]`

Then, if you change the `output_node` to `'feature_map/Conv2D'`, it will lead to a different error: `ValueError: Weight layer's name input to conv layer does not end with '/read'`

I did a little bit of investigation, it seems like the way Keras sets up the convolution kernels is different from the way Slim does it -- which is why we observe this failure. Let me take a closer look, I think there is a good chance it will not be hard to support Keras.

**Comment by andrefaraujo** [comment] 2019-12-12 23:57
Alright, as I expected it was easy to fix this. See this commit https://github.com/google-research/receptive_field/commit/a67758d3bb5053271c4e47d94179fe1dc0d56524 , which I just checked in.

Closing since I think this is resolved now, but please feel free to reopen if you are still having trouble.

**Comment by Permafacture** [comment] 2020-04-08 17:54
For other Keras users, the way I used this was:

```
# after building or loading model
import tensorflow.keras.backend as K
sesh = K.get_session()
compute_receptive_field_from_graph_def(sesh.graph_def, fieldname1, fieldname2)
```

Where I got the field names from the tensorflow graph as described above.

However, I get a number of errors:
`ValueError: Unknown layer for operation 'skip_layer_11/Tanh': Tanh`
`Sqeeze` was another unknown operation

I'm using tensorflow 1.15.2 and the version of Keras built into it

**Comment by Permafacture** [comment] 2020-04-08 18:27
@andrefaraujo I think this issue should be reopened

**Comment by andrefaraujo** [comment] 2020-04-08 18:31
Hey @Permafacture , can you try simply adding the `Tanh` op to this list: https://github.com/google-research/receptive_field/blob/master/receptive_field/python/util/parse_layer_parameters.py#L29
Since `Tanh` is an elementwise op, that should work as expected. (feel free to submit a PR as well)

Regarding `Squeeze`, are you referring to https://www.tensorflow.org/api_docs/python/tf/squeeze? I wonder in what context you are using this. In any case, the RF parameters are unchanged since you are not actually manipulating the input tensor, so one possibility is to also add it to the above list. What would be more complex is what happens after you apply the `Squeeze` op. Another possibility for you would be to measure the RF parameters before this op, although without the context I don't know if this makes sense for you.

**Comment by Permafacture** [comment] 2020-04-08 20:00
Thanks @andrefaraujo. The squeeze operation is generated by Keras. I'm not doing anything wild.  Your suggestion let the code get passed those errors but now I have:

`ValueError: Weight layer's name input to conv layer does not end with '/read' or '/Conv2D/ReadVariableOp': projection_layer/conv1d/ExpandDims_1`

I'm guessing this library just wasn't written with 1D convolutions in mind?  If it was or if it is a desire to add that, I can try to create a reproducible example.

**Comment by andrefaraujo** [comment] 2020-04-08 20:36
Indeed, this library was designed considering mainly CNNs applied on images, usually using 2D operators.

I see what's going on, IIUC you are using 1D convolutions which end up using 2D conv combined with ExpandDims under the hood.

- Can you tell me a bit more about your use-case? What type of network are you using?
- Would you be interested in helping with support for 1D signals?

**Comment by Permafacture** [comment] 2020-04-08 20:56
My network is essentially variation on WaveNet, a purely convolutional stack with no pooling or fully connected layers.  I'd like to have a canonical answer to what is the receptive field for a single output sample, so as I play with the network architecture I don't accidentally miscalculate the receptive field.

I'm happy to help with support for 1D signals.  Let me know how I can help.

**Comment by andrefaraujo** [comment] 2020-04-09 01:09
Thanks for the explanation!

Supporting 1D signals should be relatively straightforward. But let me close this and start a different thread for this, since it's unrelated to this original issue.

**Comment by hmeine** [comment] 2020-05-12 07:00
I tried to run the code on a Keras network of my own and ran into many issues. Should I re-open this issue or a new one?

**Comment by andrefaraujo** [comment] 2020-05-12 18:01
Reopened. Feel free to mention the problems here. We can branch into other issues for separate discussions later if needed.

**Comment by BurgerBecker** [comment] 2020-05-13 13:52
@andrefaraujo I've had a similar problem to previous posts regarding an unknown layer for operation:

```  File "graph_def.py", line 41, in get_flops
   print(rf.compute_receptive_field_from_graph_def(g.as_graph_def(),'conv2d_input','activation_4/Relu'))

  File "/usr/local/lib/python3.6/dist-packages/receptive_field/python/util/receptive_field_computation.py", line 274, in compute_receptive_field_from_graph_def
    node, name_to_node, node_info[node.name].input_size)

  File "/usr/local/lib/python3.6/dist-packages/receptive_field/python/util/parse_layer_parameters.py", line 341, in get_layer_params
    (node.name, node.op))

ValueError: Unknown layer for operation 'batch_normalization_3/cond': If 
```

Is this just another case I can add to the list of white-listed layer operations, which do not affect the receptive field calculations?

**Comment by andrefaraujo** [comment] 2020-05-13 16:07
@BurgerBecker I don't know for sure. At first sight, this is looking like a safe case where indeed you can add to the whitelisted set of operations. I searched around a bit, found [this thread](https://github.com/tensorflow/tensorflow/issues/31331) mentioning the variable `batch_normalization/cond/ReadVariableOp`, which is looking like a variable reading op, in which case it would indeed be totally safe.

**Comment by hmeine** [comment] 2020-05-13 20:22
I found a whole set of additional ops appearing in my model:
* Exp
* Max
* Merge
* RandomUniform
* Pack
* Sum (due to global average pooling?)
* Transpose

Furthermore, `weights_layer_read_name.endswith("/convolution/ReadVariableOp")` instead of `/Conv2D/...`.

I tried extending the code, but then I got this problem:
```
Traceback (most recent call last):
  File ".../Experiments/receptive_field_test.py", line 14, in <module>
    receptive_field.compute_receptive_field_from_graph_def(g, 'input', 'output/Identity')
  File ".../receptive_field/receptive_field/python/util/receptive_field_computation.py", line 323, in compute_receptive_field_from_graph_def
    inp_node = name_to_node[inp_name]
KeyError: 'spatial_dropout2d_11/cond/dropout/random_uniform/shape/Switch:1'
```

**Comment by andrefaraujo** [comment] 2020-05-13 20:28
@hmeine which kind of model are you using?

The error you have seems to indicate you are looking for a node name which wasn't previously found in the graph, somehow. If you have a small reproducing snippet, that would be helpful.

**Comment by BurgerBecker** [comment] 2020-05-14 06:30
> @BurgerBecker I don't know for sure. At first sight, this is looking like a safe case where indeed you can add to the whitelisted set of operations. I searched around a bit, found [this thread](https://github.com/tensorflow/tensorflow/issues/31331) mentioning the variable `batch_normalization/cond/ReadVariableOp`, which is looking like a variable reading op, in which case it would indeed be totally safe.

After adding `If` to the white-list operations, I get the error `Graph is not aligned since center shift from different paths is different in horizontal direction`. Would it mess up the effective padding calculation to give this layer undefined padding?

@andrefaraujo does batch norm affect any of the receptive field calculations? 

As an easier workaround, if I compile my Keras model without any batch norm, the effective receptive field/stride/padding calculations should be the same as with it? (Rather than having to add operations that are potentially unsafe)

**Comment by hmeine** [comment] 2020-05-14 10:20
I'm attaching a [minimal_example.zip](https://github.com/google-research/receptive_field/files/4627598/minimal_example.zip) which loads a keras model and reproduces the error(s). It's a U-net style architecture, so maybe the problem is caused by the multiple pathways, yet there is already a topological ordering in the code, so I thought that part should be covered. Thanks for looking into it!

**Comment by andrefaraujo** [comment] 2020-05-14 19:00
@BurgerBecker regarding BatchNorm affecting RF computation, see the discussion in the paper here: https://distill.pub/2019/computing-receptive-fields/#other-network-operations
In our library, we consider the inference-time case where it does not affect the RF computation.

Regarding the `Graph is not aligned since center shift from different paths is different in horizontal direction` error, you can see the discussion on alignment issues at: https://distill.pub/2019/computing-receptive-fields/#arbitrary-computation-graphs
To understand why you are getting this error, it really depends on your model -- so without context it is difficult to help. One common potential problem here is that the padding would depend on the input resolution -- have you tried running the computation by setting the `input_resolution` argument [here](https://github.com/google-research/receptive_field/blob/master/receptive_field/python/util/receptive_field_computation.py#L158)?

**Comment by andrefaraujo** [comment] 2020-05-14 19:14
@hmeine Here's what I tried, seems like your output node is invalid. 

After downloading your model to `/tmp`,

```python
$ python3
>>> import receptive_field
>>> import tensorflow as tf
>>> model = tf.keras.models.load_model('/tmp/minimal_example/keras_model.h5')
>>> g = tf.compat.v1.keras.backend.get_session().graph
>>> receptive_field.compute_receptive_field_from_graph_def(g, 'input', 'output/Identity')                                                                                                                
```

I get the following error:

```
Traceback (most recent call last):                                                                                                                                                                       
  File "<stdin>", line 1, in <module>                                                                                                                                                                    
  File "/usr/local/.../home/andrearaujo/receptive_field_library/receptive_field/receptive_field/python/util/receptive_field_computation.py", line 385, in compute_receptive_field_from_graph_def      
    raise ValueError("Output node was not found")                                                                                                                                                        
ValueError: Output node was not found               
```

**Comment by hmeine** [comment] 2020-05-18 13:01
Interesting! When I load the model with keras 2.3.1, the output node is found. When I load it with Keras 2.2.4-tf, I get the same error as you, because the output node's name is then `output/output/Identity` (with one more level of `output/`). Also, there are additional operation types complained about, such as 
* StridedSlice
* Shape

But I also get the same problem as before, which I suddenly start to understand a little better: `spatial_dropout2d_5/cond/Shape/Switch:1` may be a placeholder we introduced in order to be able to toggle dropout! So, it is kind of like a second input, the receptive field on which I am not interested in.

**Comment by BurgerBecker** [comment] 2020-06-06 10:42
@andrefaraujo Thank you for mentioning the `input_resolution` parameter, I've set that and it works well. I've removed all batch norm and dropout layers, the issues with effective padding being returned as `None` have been resolved.

I just wanted to check whether the sizes I'm getting back is realistic or whether this might be a different issue or (most probably) something that I am doing wrong. I get very large values for the Effective Receptive Field in some models, much larger than I can find for any reference model.

Here are some results that I get when testing the same model with varying stride lengths. I've added VGG16D as a sanity check. [Effective receptive field, Effective Stride, Effective Padding]

 `{'convX_erf': [90, 16, 37], 'convX_strides_erf': [46967, 32768, 14112], 'convX_strides_less_erf': [765, 256, 212], 'convX_strides_even_less_erf': [333, 64, 132, ], 'vgg16_d_erf': [212, 32, 90]}`

Is this a realistic result or is this way off?

ConvX_ERF is the baseline model with a stride length of 1 and same padding, while ConvX_strides_ERF has a stride length of 2 on every layer, ConvX_strides_less_ERF only has a stride length of 2 at the beginning of each convolutional block and ConvX_strides_even_less_ERF has a stride length of 2 only on the first two convolutional blocks.

I'd be willing to share the relevant code with you in private, since we're in the process of publication and I can't release this publicly yet, but will do so as soon as I am able.

**Comment by andrefaraujo** [comment] 2020-06-12 00:41
@BurgerBecker It's hard to tell because I have no idea what your model is doing :)

But, from the small bits of information I can understand, 

> ConvX_strides_ERF has a stride length of 2 on every layer

This will indeed produce huge RF size, if you have a sufficient number of layers.

See eq 2 in the paper. A simple convnet with all kernel sizes 3 and all strides 2 would produce an RF size of 1 + 2 + 4 + 8 + 16 ... For a total of 10 layers, that would be 2**10 - 1 RF size -- you can see the exponential growth.

**Closed as completed** 2020-06-12 00:42 UTC

**Comment by surajkothawade** [comment] 2020-08-03 18:34
I suggest that the following node should be added to _UNCHANGED_RF_LAYER_OPS for supporting keras models. Please verify.

- "Merge", "Switch", "Transpose", "Conv2DBackpropInput", "Pack", "StridedSlice", "Shape", "PlaceholderWithDefault"

Also, is there a support for Deconv layers in the RF computation?

**Comment by andrefaraujo** [comment] 2020-08-10 21:49
@surajkothawade can you give an example where these layers are needed?

There is no support for Deconv layers right now.

**Comment by divyagupta25** [comment] 2023-05-29 07:38
@BurgerBecker
My issue with `None` in effective_padding also got resolved with the `input_resolution` parameter. However, I am unable to figure out the names of the input and output nodes. Could you please help me? (cc: @andrefaraujo in case you are active) 

This is the code I am using 

```
import receptive_field as rf
import tensorflow.compat.v1 as tf
from tensorflow.keras import datasets, layers, models

# Construct graph.
g = tf.Graph()
with g.as_default():
    # x = tf.placeholder(tf.float32, shape=(1, 384, 384, 3), name='input_image')
    x = tf.keras.Input([384, 384, 3], name='input_image')
    model = models.Sequential()
    model.add(layers.Conv2D(filters=64, kernel_size=(7, 7), strides=(2, 2), activation='relu', use_bias=False, padding='same', input_shape=(384, 384, 3)))      
    model.add(layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='same'))    
    model.add(layers.Conv2D(filters=384, kernel_size=(7, 7), strides=(2, 2), activation='relu', use_bias=False, padding='same'))                             
    model.add(layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='same', name='op'))   
    output = model(x)

print(output.shape)
res = [n.name for n in g.as_graph_def().node]     ; print(res)

# Compute receptive field parameters.
rf_x, rf_y, eff_stride_x, eff_stride_y, eff_pad_x, eff_pad_y = rf.compute_receptive_field_from_graph_def(g.as_graph_def(), 'input_image', 'sequential/op/MaxPool', input_resolution=(384, 384, 3))
```

However, it works when I use `conv2d_input` and `op/MaxPool` as input and output, respectively.

**Comment by andrefaraujo** [comment] 2023-06-09 20:03
@divyagupta25 : see this colab: https://github.com/google-research/receptive_field/blob/master/RF_Keras_Applications.ipynb

Under "Bonus stuff: parsing model graph, printing nodes, etc.", the last section. That code should help you find node names.
